x-ui-common: &ui-common
  build: .
  working_dir: /usr/workspace

  volumes:
    - .:/usr/workspace

  environment:
    CHROME_BIN: /usr/bin/chromium
    CHROMEDRIVER_PATH: /usr/bin/chromedriver
    BASE_URL: ${BASE_URL:-https://www.saucedemo.com/}
    PYTEST_WORKERS: ${PYTEST_WORKERS:-2}
    STANDARD_USER: ${STANDARD_USER:?STANDARD_USER is required}
    LOCKED_OUT_USER: ${LOCKED_OUT_USER:?LOCKED_OUT_USER is required}
    SECRET_SAUCE: ${SECRET_SAUCE:?SECRET_SAUCE is required}
    INVALID_PASSWORD: ${INVALID_PASSWORD:?INVALID_PASSWORD is required}

services:
  all:
    <<: *ui-common
    command: >
      sh -c "mkdir -p logs allure-results &&
      pytest -n $$PYTEST_WORKERS
      --alluredir=allure-results --clean-alluredir"

  smoke:
    <<: *ui-common
    command: >
      sh -c "mkdir -p logs allure-results &&
      pytest -m smoke -n $$PYTEST_WORKERS
      --alluredir=allure-results --clean-alluredir"

  negative:
    <<: *ui-common
    command: >
      sh -c "mkdir -p logs allure-results &&
      pytest -m negative -n $$PYTEST_WORKERS
      --alluredir=allure-results --clean-alluredir"

  e2e:
    <<: *ui-common
    command: >
      sh -c "mkdir -p logs allure-results &&
      pytest -m e2e -n $$PYTEST_WORKERS
      --alluredir=allure-results --clean-alluredir"

  regression:
    <<: *ui-common
    command: >
      sh -c "mkdir -p logs allure-results &&
      pytest -m regression -n $$PYTEST_WORKERS
      --alluredir=allure-results --clean-alluredir"